### ISSUE TITLE
执行报错了

### ISSUE THREAD

**Issue by janglichao** [eat-or-eat/Chatgpt-Custom#3]
在jupyter运行模型训练的步骤出错：
ValueError: 150000 is not in list
---------------------------------------------------------------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[16], line 25
      1 training_args = TrainingArguments(
      2     "output",
      3     fp16 =True,
   (...)
     15     save_strategy="no"  # https://huggingface.co/docs/transformers/v4.27.2/en/main_classes/trainer#transformers.TrainingArguments.save_strategy
     16 )
     19 trainer = MymodifiedTrainer(
     20     model=model,
     21     train_dataset=mini_train_dataset,
     22     args=training_args,
     23     data_collator=data_collator,
     24 )
---> 25 trainer.train()

File ~/anaconda3/envs/chatglm-6b/lib/python3.11/site-packages/transformers/trainer.py:1633, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1628     self.model_wrapped = self.model
   1630 inner_training_loop = find_executable_batch_size(
   1631     self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size
   1632 )
-> 1633 return inner_training_loop(
   1634     args=args,
   1635     resume_from_checkpoint=resume_from_checkpoint,
   1636     trial=trial,
   1637     ignore_keys_for_eval=ignore_keys_for_eval,
   1638 )

File ~/anaconda3/envs/chatglm-6b/lib/python3.11/site-packages/transformers/trainer.py:1979, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1976     self.state.epoch = epoch + (step + 1 + steps_skipped) / steps_in_epoch
   1977     self.control = self.callback_handler.on_step_end(args, self.state, self.control)
-> 1979     self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
   1980 else:
   1981     self.control = self.callback_handler.on_substep_end(args, self.state, self.control)

File ~/anaconda3/envs/chatglm-6b/lib/python3.11/site-packages/transformers/trainer.py:2236, in Trainer._maybe_log_save_evaluate(self, tr_loss, model, trial, epoch, ignore_keys_for_eval)
   2230             metrics = self.evaluate(
   2231                 eval_dataset=eval_dataset,
   2232                 ignore_keys=ignore_keys_for_eval,
   2233                 metric_key_prefix=f"eval_{eval_dataset_name}",
   2234             )
   2235     else:
-> 2236         metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
   2237     self._report_to_hp_search(trial, self.state.global_step, metrics)
   2239 if self.control.should_save:

Cell In[13], line 98, in MymodifiedTrainer.evaluate(self, eval_dataset, ignore_keys, metric_key_prefix)
     96 # 编写自定义评估逻辑
     97 question = '你是谁'
---> 98 response, history = model.chat(tokenizer, question, history=[])
     99 print('问题:', question)
    100 print('回答:', response)

File ~/anaconda3/envs/chatglm-6b/lib/python3.11/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/.cache/huggingface/modules/transformers_modules/ChatGLM-6B/modeling_chatglm.py:1253, in ChatGLMForConditionalGeneration.chat(self, tokenizer, query, history, max_length, num_beams, do_sample, top_p, temperature, logits_processor, **kwargs)
   1251 inputs = tokenizer([prompt], return_tensors="pt")
   1252 inputs = inputs.to(self.device)
-> 1253 outputs = self.generate(**inputs, **gen_kwargs)
   1254 outputs = outputs.tolist()[0][len(inputs["input_ids"][0]):]
   1255 response = tokenizer.decode(outputs)

File ~/anaconda3/envs/chatglm-6b/lib/python3.11/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/anaconda3/envs/chatglm-6b/lib/python3.11/site-packages/transformers/generation/utils.py:1452, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, **kwargs)
   1444     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1445         input_ids=input_ids,
   1446         expand_size=generation_config.num_return_sequences,
   1447         is_encoder_decoder=self.config.is_encoder_decoder,
   1448         **model_kwargs,
   1449     )
   1451     # 13. run sample
-> 1452     return self.sample(
   1453         input_ids,
   1454         logits_processor=logits_processor,
   1455         logits_warper=logits_warper,
   1456         stopping_criteria=stopping_criteria,
   1457         pad_token_id=generation_config.pad_token_id,
   1458         eos_token_id=generation_config.eos_token_id,
   1459         output_scores=generation_config.output_scores,
   1460         return_dict_in_generate=generation_config.return_dict_in_generate,
   1461         synced_gpus=synced_gpus,
   1462         **model_kwargs,
   1463     )
   1465 elif is_beam_gen_mode:
   1466     if generation_config.num_return_sequences > generation_config.num_beams:

File ~/anaconda3/envs/chatglm-6b/lib/python3.11/site-packages/transformers/generation/utils.py:2465, in GenerationMixin.sample(self, input_ids, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   2462         break
   2464 # prepare model inputs
-> 2465 model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
   2467 # forward pass to get next token
   2468 outputs = self(
   2469     **model_inputs,
   2470     return_dict=True,
   2471     output_attentions=output_attentions,
   2472     output_hidden_states=output_hidden_states,
   2473 )

File ~/.cache/huggingface/modules/transformers_modules/ChatGLM-6B/modeling_chatglm.py:1089, in ChatGLMForConditionalGeneration.prepare_inputs_for_generation(self, input_ids, past, past_key_values, attention_mask, position_ids, **kwargs)
   1087 use_gmask = True if gMASK in input_ids else False
   1088 seqs = input_ids.tolist()
-> 1089 mask_positions = [seq.index(mask_token) for seq in seqs]
   1091 # only last token for input_ids if past is not None
   1092 if past is not None or past_key_values is not None:

File ~/.cache/huggingface/modules/transformers_modules/ChatGLM-6B/modeling_chatglm.py:1089, in <listcomp>(.0)
   1087 use_gmask = True if gMASK in input_ids else False
   1088 seqs = input_ids.tolist()
-> 1089 mask_positions = [seq.index(mask_token) for seq in seqs]
   1091 # only last token for input_ids if past is not None
   1092 if past is not None or past_key_values is not None:

ValueError: 150000 is not in list

**Comment by morning-hao** [comment]
环境问题:
1.可能是transformer的版本问题
2.可能是modeling_chatglm.py更新了的问题，上传的代码里面已经不是最新的了
